### ISSUE TITLE
checkRep() in Event causes problems

### ISSUE THREAD

**Issue by sheend** [sheend/blast#10]
Its been commented out for now, don't really know the cause of the issue, but if you can debug through that would be great

**Comment by sheend** [comment]
Check with @michellelee4649 or @mkhuat for details on why it doesn't work with firebase

**Comment by graceqiu** [comment]
@mkhuat Michelle explained to me how Firebase parses an Event, but I don't know anything about updating events through Firebase (since fields are parsed in constructors.) Could I get help on how to update through Firebase, or would it be easier if you did it?

**Comment by mkhuat** [comment]
What do you mean by update through Firebase? Are there new fields that need
to be added to the Event/User object classes? Michelle can work on it in
that case!

**Comment by mkhuat** [comment]
correction: Michelle and I\* (both of us)

**Comment by graceqiu** [comment]
@michellelee4649 Said that "There's another thing that firebase has for updating events when we want to modify an existing event." The commented out (bad) checkReps() belong in the methods that update an Event, so I assumed it's because we're updating incorrectly/not using Firebase?
