### ISSUE TITLE
CreateEventActivity "edit priveleges"

### ISSUE THREAD

**Issue by sheend** [sheend/blast#11]
I don't think we need to worry about this atm, but it's especially harmful to have null title because any new create page automatically makes the title unchangeable.
Maybe we can save this for later, or fix it to make first time creates still have titles and all.

**Comment by graceqiu** [comment]
Is this referring to the fact that the boolean Intent extra doesn't work? Not sure where this null title is.

**Comment by sheend** [comment]
The if/else branch was commented out so it's not doing that anymore, but this needs to be fixed because firebase crashes the app for a null title

**Comment by carsonus** [comment]
My validation seems to be preventing a null title right now
