### ISSUE TITLE
UI Create Event data validation

### ISSUE THREAD

**Issue by mkhuat** [sheend/blast#20]
The CreateEventAcitivity needs to check that all fields have been filled out correctly.

Right now, the application crashes if any of the fields are empty because firebase needs all fields to be non-null.

**Comment by carsonus** [comment]
Grace and I are working on it

**Comment by graceqiu** [comment]
(Sorry I just got really confused)

**Comment by carsonus** [comment]
Done enough for beta release. Does not enforce correct input yet
