### ISSUE TITLE
Sliding animation is wrong

### ISSUE THREAD

**Issue by sheend** [sheend/blast#24]
It pops up which is wrong, we need to figure out the sliding right thing without breaking the event transition to the detail acitvity

**Comment by graceqiu** [comment]
Clarification: when you say sliding, do you mean users should be able to drag their fingers across the screen and change activities, or do you just mean the animation itself should be a slide right?

**Comment by sheend** [comment]
The transition going to the detail activity slides right, but the animation coming back is still the old one

**Comment by graceqiu** [comment]
Kay gonna fix that

**Comment by sheend** [comment]
Looks great!
