### ISSUE TITLE
Commenting DetailActivity

### ISSUE THREAD

**Issue by sheend** [sheend/blast#3]
Method comments for what our method does specifically, not the generic Android method comment
Inline comments every time we use a new interesting/potentially confusing thing
//TODO on everything that is hardcoded and needs to be changed in the future
Nothing for the layout files, but you can mention any of those things in the activity comments if necessary

Yo @michellelee4649

**Comment by michellelee4649** [comment]
@graceqiu I commented MainActivity and DetailActivity. You can add more if I missed anything!
