### ISSUE TITLE
Getting Serializable Event

### ISSUE THREAD

**Issue by sheend** [sheend/blast#7]
private Event event = (Event) getIntent().getSerializableExtra("event");
The line has been commented out because of the following stack trace below
Please only push to the ui branch when you fix it

java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{cse403.blast/cse403.blast.DetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.content.Intent.getSerializableExtra(java.lang.String)' on a null object reference

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.content.Intent.getSerializableExtra(java.lang.String)' on a null object reference
at cse403.blast.DetailActivity.<init>(DetailActivity.java:27)

**Comment by graceqiu** [comment]
Fixed, cannot call getIntent() in field initialization, can only call getIntent() in onCreate() so that's where the initialization of the event field is now.
